version: "3.7"
services:
  flask-app:
   build: ./application
   container_name: application 
   ports:
   - target: 5000
     published: 5000
     protocol: tcp
  nginx:
   image: nginx:latest
   container_name: appnginx
   ports:
   - target: 80
     published: 80
     protocol: tcp
   volumes:
     - type: bind
       source: ./nginx/nginx.conf
       target: /etc/nginx/nginx.conf
  mysql:
    build: ./db
    container_name: mysql

  







