# Use Python 3.6 or later as a base image
FROM python:3.7
# make workign directory 
WORKDIR /frontendtest
# Copy contents into image
 COPY . .
# Install pip dependencies from requirements
RUN pip install -r "requirements.txt"
ARG LOISPWD 
# Set environment variable
ENV MYSQL_USER "loistries"
ENV MYSQL_PWD "$LOISPWD"
ENV MYSQL_IP "loistries.mysql.database.azure.com"
ENV MYSQL_DB "loistries"
ENV MYSQL_SK "gtdxtrdfyhfhyfyf"

# Expose the correct port
EXPOSE 5000
# Create an entrypoint
ENTRYPOINT [ "python" , "app.py"]