version: "3.7"
services:
  mysql:
     image: mysql:5.7
     build: ./db
     container_name: mysql
     environment:
        - MYSQL_ROOT_PASSWORD=${loispwd}
  frontend:
    build: ./frontend
    environment:
      - MYSQL_PWD=${loispwd}
    container_name: application 
    ports:
    - target: 5000
      published: 5000
      protocol: tcp
    depends_on:
     - mysql
  service1:
    build: ./service1
    container_name: serviceone 
    ports:
    - target: 5001
      published: 5001
      protocol: tcp 
  service2:
    build: ./service2
    container_name: servicetwo
    ports:
    - target: 5002
      published: 5002
      protocol: tcp
  nginx:
   image: nginx:latest
   container_name: appnginx
   ports:
   - target: 80
     published: 80
     protocol: tcp
   volumes:
     - type: bind
       source: ./nginx/nginx.conf
       target: /etc/nginx/nginx.conf
  backend:
   build: ./backend
   container_name: backend 
   ports:
   - target: 5003
     published: 5003
     protocol: tcp

  







