version: "3.7"
services:
  mysql:
     image: mysql:5.7
     build: ./db
     container_name: mysql
     environment:
        - MYSQL_ROOT_PASSWORD=${loispwd}
  frontend:
    build: ./frontend
    image: loiss/application:latest
    environment:
      - MYSQL_PWD=${loispwd}
    container_name: application 
    ports:
    - target: 5000
      published: 5000
      protocol: tcp
    depends_on:
     - mysql
  service1:
    build: ./service1
    image: loiss/service1:latest
    container_name: serviceone 
    ports:
    - target: 5001
      published: 5001
      protocol: tcp 
  service2:
    build: ./service2
    image: loiss/service2:latest
    container_name: servicetwo
    ports:
    - target: 5002
      published: 5002
      protocol: tcp
  backend:
   build: ./backend
   image: loiss/backend:latest
   container_name: backend 
   ports:
   - target: 5003
     published: 5003
     protocol: tcp

  







