version: "3.7"
services:
  frontend:
    build: ./frontend
    image: loiss/loissp:frontend
    container_name: application 
    ports:
    - target: 5000
      published: 5000
      protocol: tcp
  service1:
    build: ./service1
    image: loiss/loissp:serviceone
    container_name: serviceone 
    ports:
    - target: 5001
      published: 5001
      protocol: tcp 
  service2:
    build: ./service2
    image: loiss/loissp:servicetwo
    container_name: servicetwo
    ports:
    - target: 5002
      published: 5002
      protocol: tcp  
  backend:
   build: ./backend
   image: loiss/loissp:backend
   container_name: backend 
   ports:
   - target: 5003
     published: 5003
     protocol: tcp

  







